# Generated by Django 4.1.2 on 2022-10-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swepApp', '0003_rename_description_recipe_modopreparo_recipe_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='regiao',
            field=models.CharField(choices=[('NO', 'Norte'), ('NE', 'Nordeste'), ('CO', 'Centro-Oeste'), ('SU', 'Sul'), ('SD', 'Sudeste')], max_length=2, null=True),
        ),
    ]
