# Generated by Django 4.1.2 on 2022-10-21 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swepApp', '0005_indicacoes_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userswep',
            name='idade',
        ),
        migrations.AddField(
            model_name='userswep',
            name='is_nutritionist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userswep',
            name='is_regular',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='indicacoes',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredientes',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='regiao',
            field=models.CharField(choices=[('NO', 'Norte'), ('NE', 'Nordeste'), ('CO', 'Centro-Oeste'), ('SU', 'Sul'), ('SE', 'Sudeste')], max_length=2, null=True),
        ),
    ]
