# Generated by Django 4.1.2 on 2022-10-22 12:22

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swepApp', '0006_remove_userswep_idade_userswep_is_nutritionist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('valorNutri', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Despensa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alimentos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swepApp.alimentos')),
            ],
        ),
        migrations.CreateModel(
            name='Nutritionist',
            fields=[
                ('userswep_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('crn', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('swepApp.userswep',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='userswep',
            name='is_regular',
        ),
        migrations.CreateModel(
            name='RegularUser',
            fields=[
                ('userswep_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('despensa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='swepApp.despensa')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('swepApp.userswep',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredientes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swepApp.alimentos'),
        ),
    ]
