# Generated by Django 4.1.2 on 2022-10-22 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swepApp', '0007_alimentos_despensa_nutritionist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularuser',
            name='despensa',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='swepApp.despensa'),
        ),
    ]
