# Generated by Django 4.1.1 on 2022-10-22 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swepApp', '0008_alter_regularuser_despensa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userswep',
            name='is_nutritionist',
        ),
        migrations.RemoveField(
            model_name='despensa',
            name='alimentos',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredientes',
        ),
        migrations.AddField(
            model_name='despensa',
            name='alimentos',
            field=models.ManyToManyField(to='swepApp.alimentos'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredientes',
            field=models.ManyToManyField(to='swepApp.alimentos'),
        ),
    ]
