# Generated by Django 4.1.1 on 2022-10-23 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swepApp', '0009_remove_userswep_is_nutritionist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredientes',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredientes',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
