# Generated by Django 4.1.2 on 2022-10-24 14:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('swepApp', '0011_alter_recipe_regiao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alimentos',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='alimentos',
            name='valorNutri',
        ),
        migrations.AddField(
            model_name='alimentos',
            name='alimentos',
            field=models.TextField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
