name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: grupoSWEP/SWEP@v3.12.12 # This is the action
        with:
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME_GIT }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_email_address: "los2@cesar.school"
